version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.nuxt.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped 