FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port
EXPOSE 3000

# Set the host to 0.0.0.0 to make the server accessible from outside the container
ENV HOST=0.0.0.0
ENV PORT=3000
ENV NODE_ENV=development

# Prepare Nuxt
RUN npm run postinstall

# Start Nuxt in development mode
CMD ["npm", "run", "dev"] 