version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.nuxt.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped 